version: '3.8'

services:
  postgis:
    image: 'postgis/postgis:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
