
CREATE TABLE event
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    eventtitle          VARCHAR(100)                             NOT NULL,
    eventtext           VARCHAR(100)                             NOT NULL,
    cityname            VARCHAR(255),
    eventdate           TIMESTAMP WITHOUT TIME ZONE,
    event_appuser_id_fk INTEGER                                  NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE eventjoining
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id_fk   INTEGER                                  NOT NULL,
    appuser_id_fk INTEGER                                  NOT NULL,
    CONSTRAINT pk_eventjoining PRIMARY KEY (id)
);
ALTER TABLE eventjoining
    ADD CONSTRAINT uc_dcc162d0a06bf3198f75f4725 UNIQUE (event_id_fk, appuser_id_fk);

ALTER TABLE eventjoining
    ADD CONSTRAINT FK_EVENTJOINING_ON_APPUSER_ID_FK FOREIGN KEY (appuser_id_fk) REFERENCES appuser (id);

ALTER TABLE eventjoining
    ADD CONSTRAINT FK_EVENTJOINING_ON_EVENT_ID_FK FOREIGN KEY (event_id_fk) REFERENCES event (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_EVENT_APPUSER_ID_FK FOREIGN KEY (event_appuser_id_fk) REFERENCES appuser (id) ON DELETE CASCADE;