CREATE TABLE appuser
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(100)                             NOT NULL,
    password_hash        VARCHAR(60)                              NOT NULL,
    email                VARCHAR(100)                             NOT NULL,
    appuser_access_id_fk INTEGER                                  NOT NULL REFERENCES access (id),
    CONSTRAINT pk_appuser PRIMARY KEY (id)

);