CREATE TABLE fish
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 TEXT                                     NOT NULL,
    species              TEXT                                     NOT NULL,
    description          TEXT                                     NOT NULL,
    fish_watertype_id_fk INTEGER                                  NOT NULL REFERENCES watertype(id),
    fish_sex_id_fk       INTEGER                                  NOT NULL REFERENCES sex(id),
    fish_appuser_id_fk   INTEGER                                  NOT NULL REFERENCES appuser(id),
    CONSTRAINT pk_fish PRIMARY KEY (id)
);
