CREATE TABLE IF NOT EXISTS watertype
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                     NOT NULL,
    CONSTRAINT pk_watertype PRIMARY KEY (id)
)