CREATE TABLE post
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            TEXT                                     NOT NULL,
    post_fish_id_fk INTEGER                                  NOT NULL REFERENCES fish (id),
    CONSTRAINT pk_post PRIMARY KEY (id)
);
